version: "3.1"

services:
  api:
    container_name: api
    build: ./
    command: npm run start:dev
    ports:
      - "3000:3000"

 nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - api


volumes:
  redis_data: